scrape_configs:
  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:8000']
        labels:
          application: 'java-spring-mongo-rest-ref'
    basic_auth:
      username: user
      password: password